# NumPy Arrays  

* NumPy arrays are the main way.
* NumPy arrays essentially come in two flavors: vectors and metrices.
* Vectors are strictly 1-d arrays and matrices are 2-d

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_matrices = [[1,2,3], [4,5,6],[7,8,9]] # nested list

In [8]:
type(my_matrices)

list

In [9]:
np.array(my_matrices) # now 2-d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
type(np.array(my_matrices))

numpy.ndarray

In [11]:
#create arrays faster

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10) #one dimensional array 10 evenly space

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

np.eye(4)

np.random.rand() means,
**np** comes from **numPy**
random generates random values
**rand()** means uniform distribution from 0 to 1

**randn()** means standard normal distribution center around 0

In [19]:
np.random.rand(5)  # random samples unifor distribuotuon from 0 to 1
                   # it created 1 row - 5 column array

array([0.00344905, 0.12899727, 0.9053465 , 0.43967133, 0.77267079])

In [20]:
np.random.rand(5,5) # this will create 5X5  metrix (2d array)

array([[0.63265793, 0.14106319, 0.56159194, 0.159165  , 0.05709457],
       [0.49774959, 0.29092082, 0.63470133, 0.50147287, 0.92915834],
       [0.24140481, 0.4958201 , 0.02272412, 0.48049858, 0.94814922],
       [0.616286  , 0.71079536, 0.90740358, 0.76129467, 0.76336171],
       [0.01759472, 0.42080266, 0.85496992, 0.19319303, 0.67985579]])

In [21]:
np.random.randn(2) # 1d 

array([-0.72506709,  0.62205596])

In [22]:
np.random.randn(2,2) #2d

array([[-1.34114652,  1.54463209],
       [-1.78321246,  0.55512677]])

In [23]:
np.random.randint(1,100) # it will bring random integer 
                         # between 1(inlc) and 100(excl)

78

In [24]:
np.random.randint(1,100,10)

array([61, 94, 71, 90, 59, 14, 92, 50, 32, 22])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([ 0, 22, 44, 25, 29, 38, 22,  9, 22, 31])

In [31]:
arr.reshape(5,5) # it reshapes your array as you want nXn matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max() # max value of the array

44

In [33]:
ranarr.min() # min value of the array

0

In [34]:
ranarr

array([ 0, 22, 44, 25, 29, 38, 22,  9, 22, 31])

In [36]:
ranarr.argmax()  # tells the location of mac value on the array

2

In [37]:
ranarr.argmin()

0

In [39]:
arr.shape  # means 25 col X 1 row

(25,)

In [41]:
arr = arr.reshape(5,5) # change it to 5X5

In [43]:
arr.shape  # now it shows 5X5 array

(5, 5)

In [45]:
arr.dtype  # telss the type of the values in array

dtype('int64')

In [48]:
from numpy.random import randint  # to call specific function from specific library

In [47]:
randint(2,10)

3

### NumPy Array Indexing & Selection

In [49]:
import numpy as np

In [52]:
arr = np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[8]  # it works similar to python list

8

In [55]:
arr[1:5]

array([1, 2, 3, 4])

In [57]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [58]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [59]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [61]:
arr[5:]  # this is grab everything beyond 5, where 5 is the 6th value!!

array([ 5,  6,  7,  8,  9, 10])

In [66]:
arr[0:5] = 100 # this will broadcast the value 100 for first 5 vlaue

In [65]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [67]:
arr = np.arange(0,11)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
slice_of_arr = arr[0:6]

In [70]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [71]:
slice_of_arr [:] = 99

In [72]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [73]:
arr  # numpy added these 99 values to original arrays as well. less space

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_copy = arr.copy() # to prevent it, first copy the array

In [75]:
arr_copy[:] = 100  # then you cn change it

In [78]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [79]:
arr  # and the original array will not change

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [81]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])

In [82]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
arr_2d[0][0]  # you call the first row and 1st column
                # this is 1. option to call a value from array

5

In [87]:
arr_2d[0]

array([ 5, 10, 15])

In [88]:
arr_2d[1][1]

25

In [90]:
arr_2d[2,1] # this call 2nd raw and 1st column from the array
            # this is the 2. option to call a value from array

40

In [91]:
arr_2d[1,2]

30

In [93]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [94]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

### Conditional selection

In [95]:
arr = np.arange(1,11)

In [96]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
 bool_arr =arr > 5 # will return array of boolean values

In [100]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [102]:
arr[bool_arr] # it brings only true balues in boolen array, the same indexed vlaues

array([ 6,  7,  8,  9, 10])

In [103]:
arr[arr<3]

array([1, 2])

In [106]:
arr_2d = np.arange(50).reshape(5,10)

In [107]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [108]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

### NumPy Operations

* Array with arra
* Array with Scalars
* Universal Array Functions

In [109]:
arr = np.arange(0,11)

In [110]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [112]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [113]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [115]:
arr +100  # this is scalar operation

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [116]:
arr / arr

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [117]:
1/ arr

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [118]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [119]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [120]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [121]:
np.max(arr)  # this is same 

10

In [122]:
np.log(arr)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])